server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: service-user-route
            uri: lb://user-microservice
            predicates:
              - Path=/api/v1/users/**, /api/v1/auth/**
            filters:
              - StripPrefix=0

          - id: service-home-route
            uri: lb://home-microservice
            predicates:
              - Path=/api/v1/categories/**, /api/v1/cities/**, /api/v1/departments/**, /api/v1/locations/**, /api/v1/neighborhoods/**, /api/v1/properties/**
            filters:
              - StripPrefix=0

          - id: service-visits-route
            uri: lb://service-visits
            predicates:
              - Path=/api/v1/visits/**
            filters:
              - StripPrefix=0

          - id: service-transactions-route
            uri: lb://service-transactions
            predicates:
              - Path=/api/v1/transactions/**
            filters:
              - StripPrefix=0


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}
    prefer-ip-address: true


app:
  jwt:
    secret: ${JWT_SECRET:secret}
    expiration: ${JWT_EXPIRATION:3600}
    token-prefix: ${JWT_TOKEN_PREFIX:Bearer }
    header-string: ${JWT_HEADER_STRING:Authorization}
    token-type: ${JWT_TOKEN_TYPE:JWT}