server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:

      mvc:
        routes:
          - id: service-user-route
            uri: lb://user-microservice
            predicates:
              - Path=/api/v1/users/**, /api/v1/auth/**
            # filters:
            #   - StripPrefix=0 # Ajusta según sea necesario

          - id: service-home-route
            uri: lb://home-microservice
            predicates:
              - Path=/api/v1/categories/**, /api/v1/cities/**, /api/v1/departments/**, /api/v1/locations/**, /api/v1/neighborhoods/**, /api/v1/properties/**
            # filters:
            #   - StripPrefix=0 # Ajusta según sea necesario

          - id: service-visits-route
            uri: lb://service-visits
            predicates:
              - Path=/api/v1/visits/**
            # filters:
            #   - StripPrefix=0 # Ajusta según sea necesario

          - id: service-transactions-route
            uri: lb://service-transactions
            predicates:
              - Path=/api/v1/transactions/**
            # filters:
            #   - StripPrefix=0 # Ajusta según sea necesario

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_JWT_ISSUER_URI:http://user-microservice}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.pragma.gateway360.config: DEBUG
    com.nimbusds.jose: DEBUG

app:
  jwt:
    secret: ${APP_JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
    expiration-ms: ${APP_JWT_EXPIRATION_MS:86400000}
    prefix: ${APP_JWT_PREFIX:Bearer }
    header-string: ${APP_JWT_HEADER_STRING:Authorization}
    # token-type: ${APP_JWT_TOKEN_TYPE:JWT} # Usualmente no es necesario configurarlo