spring:
  application:
    name: user-microservice
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/services_user}
    username: ${SPRING_DATASOURCE_USERNAME:karenyulier}
    password: ${SPRING_DATASOURCE_PASSWORD:12345678}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}


  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}


springdoc:
  swagger-ui:
    path: /swagger-ui.html

# JWT Configuration
app:
  jwt:
    secret: ${APP_JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
    expiration-ms: ${APP_JWT_EXPIRATION_MS:86400000}
    header: ${APP_JWT_HEADER_STRING:Authorization}
    prefix: ${APP_JWT_PREFIX:Bearer }
    issuer-uri: ${APP_JWT_ISSUER_URI:http://user-microservice}

# Server
server:
  port: ${SERVER_PORT:8081}

# Eureka
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

# Default user for data initialization (can be overridden by environment variables)
app.default-user:
  email: ${DEFAULT_USER_EMAIL:admin@example.com}
  password: ${DEFAULT_USER_PASSWORD:DefaultPassword123}
  firstName: ${DEFAULT_USER_FIRSTNAME:Admin}
  lastName: ${DEFAULT_USER_LASTNAME:User}
  documentId: ${DEFAULT_USER_DOCUMENTID:00000000}
  phoneNumber: ${DEFAULT_USER_PHONENUMBER:+1000000000}