spring:
  application:
    name: service-visits
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/visits_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:db_app_user}
    password: ${SPRING_DATASOURCE_PASSWORD:db_app_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

server:
  port: ${SERVER_PORT:8083}

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.uuid}